package pl.bookstore.hibernatemodel;
// Generated 2018-04-16 11:57:08 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Book implements java.io.Serializable {

	private static final long serialVersionUID = 0;
	private Integer id;
	private String isbn;
	private String title;
	private BigDecimal price;
	private int amount;
	private boolean available;
	private String description;
	private String link;
	
	private Publisher publisher;
	private Set orderitems = new HashSet(0);
	private Set authors = new HashSet(0);
	private Set categories = new HashSet(0);

	public Book() {
	}

	public Book(Publisher publisher, String isbn, String title, BigDecimal price, int amount, boolean available,
			String description, String link) {
		this.publisher = publisher;
		this.isbn = isbn;
		this.title = title;
		this.price = price;
		this.amount = amount;
		this.available = available;
		this.description = description;
		this.link = link;
	}

	public Book(Publisher publisher, String isbn, String title, BigDecimal price, int amount, boolean available,
			String description, String link, Set orderitems, Set authors, Set categories) {
		this.publisher = publisher;
		this.isbn = isbn;
		this.title = title;
		this.price = price;
		this.amount = amount;
		this.available = available;
		this.description = description;
		this.link = link;
		this.orderitems = orderitems;
		this.authors = authors;
		this.categories = categories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public boolean isAvailable() {
		return this.available;
	}

	public void setAvailable(boolean available) {
		this.available = available;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Set getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set orderitems) {
		this.orderitems = orderitems;
	}

	public Set getAuthors() {
		return this.authors;
	}

	public void setAuthors(Set authors) {
		this.authors = authors;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
