package pl.bookstore.hibernatemodel;
// Generated 2018-04-16 11:57:08 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Category implements java.io.Serializable {

	private static final long serialVersionUID = 0;
	private Integer id;
	private boolean visible;
	private String name;
	private Set books = new HashSet(0);

	public Category() {
	}

	public Category(boolean visible, String name) {
		this.visible = visible;
		this.name = name;
	}

	public Category(boolean visible, String name, Set books) {
		this.visible = visible;
		this.name = name;
		this.books = books;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}
