package pl.bookstore.hibernatemodel;
// Generated 2018-04-16 11:57:08 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orderinfo generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Orderinfo implements java.io.Serializable {

	private static final long serialVersionUID = 0;
	private Integer id;
	private Date created;
	private Date finished;
	private String deliveryAddress;
	private BigDecimal deliveryFee;
	private BigDecimal totalBookPrice;
	private Deliverer deliverer;
	private Statusinfo statusinfo;
	private User user;
	private Set orderitems = new HashSet(0);

	public Orderinfo() {
	}

	public Orderinfo(Statusinfo statusinfo, Date created, BigDecimal totalBookPrice) {
		this.statusinfo = statusinfo;
		this.created = created;
		this.totalBookPrice = totalBookPrice;
	}

	public Orderinfo(Deliverer deliverer, Statusinfo statusinfo, User user, Date created, Date finished,
			String deliveryAddress, BigDecimal deliveryFee, BigDecimal totalBookPrice, Set orderitems) {
		this.deliverer = deliverer;
		this.statusinfo = statusinfo;
		this.user = user;
		this.created = created;
		this.finished = finished;
		this.deliveryAddress = deliveryAddress;
		this.deliveryFee = deliveryFee;
		this.totalBookPrice = totalBookPrice;
		this.orderitems = orderitems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Deliverer getDeliverer() {
		return this.deliverer;
	}

	public void setDeliverer(Deliverer deliverer) {
		this.deliverer = deliverer;
	}

	public Statusinfo getStatusinfo() {
		return this.statusinfo;
	}

	public void setStatusinfo(Statusinfo statusinfo) {
		this.statusinfo = statusinfo;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getFinished() {
		return this.finished;
	}

	public void setFinished(Date finished) {
		this.finished = finished;
	}

	public String getDeliveryAddress() {
		return this.deliveryAddress;
	}

	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	public BigDecimal getDeliveryFee() {
		return this.deliveryFee;
	}

	public void setDeliveryFee(BigDecimal deliveryFee) {
		this.deliveryFee = deliveryFee;
	}

	public BigDecimal getTotalBookPrice() {
		return this.totalBookPrice;
	}

	public void setTotalBookPrice(BigDecimal totalBookPrice) {
		this.totalBookPrice = totalBookPrice;
	}

	public Set getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set orderitems) {
		this.orderitems = orderitems;
	}

}
