package pl.bookstore.hibernatemodel;
// Generated 2018-04-16 11:57:08 by Hibernate Tools 5.2.8.Final

/**
 * OrderitemId generated by hbm2java
 */
public class OrderitemId implements java.io.Serializable {

	private static final long serialVersionUID = 0;
	private int orderId;
	private int bookId;

	public OrderitemId() {
	}

	public OrderitemId(int orderId, int bookId) {
		this.orderId = orderId;
		this.bookId = bookId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderitemId))
			return false;
		OrderitemId castOther = (OrderitemId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getBookId() == castOther.getBookId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getBookId();
		return result;
	}

}
