package pl.bookstore.hibernatemodel;
// Generated 2018-04-16 11:57:08 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private static final long serialVersionUID = 0;
	private OrderitemId id;
	private Book book;
	private Orderinfo orderinfo;
	private int amount;
	private BigDecimal price;

	public Orderitem() {
	}

	public Orderitem(OrderitemId id, Book book, Orderinfo orderinfo, int amount, BigDecimal price) {
		this.id = id;
		this.book = book;
		this.orderinfo = orderinfo;
		this.amount = amount;
		this.price = price;
	}

	public OrderitemId getId() {
		return this.id;
	}

	public void setId(OrderitemId id) {
		this.id = id;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Orderinfo getOrderinfo() {
		return this.orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
